{
  "openapi": "3.0.3",
  "info": {
    "title": "Time Off Balances",
    "description": "Balance API which enables clients to fetch available balances for time types, time accounts and time accounts on termination.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://{api-server}",
      "description": "REST APIs for the SuccessFactors Data Centers",
      "variables": {
        "api-server": {
          "description": "SuccessFactors Data Center host",
          "default": "apisalesdemo2.successfactors.eu"
        }
      }
    }
  ],
  "paths": {
    "/rest/timemanagement/absence/v1/timeAccountBalances": {
      "get": {
        "summary": "Gets time accounts with their respective balances.",
        "description": "Gets time accounts of the entered user with their respective balances. If no user is entered, the logged in user is used.",
        "tags": [
          "Time Account Balances"
        ],
        "parameters": [
          {
            "name": "$at",
            "in": "query",
            "required": true,
            "description": "The date for which the balances are requested. The date must be in the format YYYY-MM-DD.",
            "schema": {
              "type": "string",
              "example": "2020-03-17"
            }
          },
          {
            "name": "assignmentId",
            "in": "query",
            "required": false,
            "description": "The assignmentUUID of the user for whom the balances are requested. If no user is entered, the logged in user is used.",
            "schema": {
              "type": "string",
              "example": "08F824D550FC40C9AACA7D4760C5AA3C"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "It indicates that the request was successful. The response contains the time accounts with their respective balances.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "value": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/TimeAccountBalanceResponse"
                      }
                    }
                  },
                  "example": {
                    "value": [
                      {
                        "timeAccount": {
                          "timeAccountType": {
                            "externalCode": "VAC-DAYS",
                            "externalName": "Leave Account for Vacation",
                            "unit": "DAYS"
                          },
                          "externalCode": "92f29d6bfafb40ac8cbca033744f50ad",
                          "bookableStartDate": "2023-01-01",
                          "bookableEndDate": "2024-06-30",
                          "nextTransferDate": null
                        },
                        "balances": {
                          "available": {
                            "value": 23.533,
                            "formattedWithUnit": "23.533 days",
                            "formattedWithUnitRoundedDown": "23.53 days"
                          },
                          "accrued": {
                            "value": 0,
                            "formattedWithUnit": "0 days",
                            "formattedWithUnitRoundedDown": "0 days"
                          },
                          "earned": {
                            "value": 25.033,
                            "formattedWithUnit": "25.033 days",
                            "formattedWithUnitRoundedDown": "25.03 days"
                          },
                          "paidOut": {
                            "value": 0,
                            "formattedWithUnit": "0 days",
                            "formattedWithUnitRoundedDown": "0 days"
                          },
                          "planned": {
                            "value": 0,
                            "formattedWithUnit": "0 days",
                            "formattedWithUnitRoundedDown": "0 days"
                          },
                          "taken": {
                            "value": 1.5,
                            "formattedWithUnit": "1.5 days",
                            "formattedWithUnitRoundedDown": "1.5 days"
                          }
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "403": {
            "$ref": "#/components/responses/403"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      }
    },
    "/rest/timemanagement/absence/v1/timeTypeBalances": {
      "get": {
        "summary": "Gets time types with their respective balances.",
        "description": "Gets time types of the active user with their respective balances. If specified, only the balances of the main absence time type is returned.",
        "parameters": [
          {
            "name": "$at",
            "in": "query",
            "required": true,
            "description": "The date for which the balances are requested. The date must be in the format YYYY-MM-DD.",
            "schema": {
              "type": "string",
              "example": "2020-03-17"
            }
          },
          {
            "name": "mainAbsenceTimeTypeBalanceOnly",
            "in": "query",
            "required": false,
            "description": "If true, only the balances of the main absence time type are returned.",
            "schema": {
              "type": "boolean",
              "default": false,
              "example": false
            }
          },
          {
            "name": "favoriteTimeTypeBalances",
            "in": "query",
            "required": false,
            "description": "If true, only the balances of the favorite time types are returned. If false, the balances of non-favorite time types are returned. If not specified, the balances of all time types are returned.",
            "schema": {
              "type": "boolean",
              "default": null,
              "example": false
            }
          }
        ],
        "tags": [
          "Time Type Balances"
        ],
        "responses": {
          "200": {
            "description": "It indicates that the request was successful. The response contains the time types with their respective balances.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "value": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/TimeTypeBalanceResponse"
                      }
                    }
                  },
                  "example": {
                    "value": [
                      {
                        "mainAbsenceTimeTypeBalance": true,
                        "favoriteTimeTypeBalance": false,
                        "timeType": {
                          "externalCode": "VAC",
                          "externalName": "Vacation",
                          "unit": "DAYS",
                          "leaveOfAbsence": false,
                          "undeterminedEndDateAllowed": false
                        },
                        "balance": {
                          "value": 23.533,
                          "formattedWithUnit": "23.533 days",
                          "formattedWithUnitRoundedDown": "23.53 days"
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "403": {
            "$ref": "#/components/responses/403"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      }
    },
    "/rest/timemanagement/absence/v1/terminationTimeAccountBalances": {
      "get": {
        "summary": "Gets time accounts with their respective termination balances.",
        "description": "Gets time accounts of the entered user with their respective termination balances. If no user is entered, the logged in user is used.",
        "tags": [
          "Termination Time Account Balances"
        ],
        "parameters": [
          {
            "name": "$at",
            "in": "query",
            "required": false,
            "description": "The termination date for which the balances are requested for the user. The date must be in the format YYYY-MM-DD. If no date is entered, the termination date is derived by the system and the balances on this date are returned. The date is mandatory when the API is called with preview=true.",
            "schema": {
              "type": "string",
              "example": "2020-03-17"
            }
          },
          {
            "name": "assignmentId",
            "in": "query",
            "required": false,
            "description": "The assignmentUUID of the user for whom the balances are requested. If no user is entered, the logged in user is used.",
            "schema": {
              "type": "string",
              "example": "08F824D550FC40C9AACA7D4760C5AA3C"
            }
          },
          {
            "name": "preview",
            "in": "query",
            "required": false,
            "description": "Indicator whether the termination shall be simulated if the user has not been terminated for the given date. If no value is entered, the preview is defaulted to false. Preview can only be used if there is no termination at the provided date, otherwise the request will fail.",
            "schema": {
              "type": "boolean",
              "example": "true"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "It indicates that the request was successful. The response contains the time accounts with their respective termination balances.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "value": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/TerminationTimeAccountBalanceResponse"
                      }
                    }
                  },
                  "example": {
                    "value": [
                      {
                        "timeAccount": {
                          "timeAccountType": {
                            "externalCode": "VAC-DAYS",
                            "externalName": "Leave Account for Vacation",
                            "unit": "DAYS"
                          },
                          "externalCode": "92f29d6bfafb40ac8cbca033744f50ad",
                          "bookableStartDate": "2023-01-01",
                          "bookableEndDate": "2024-06-30"
                        },
                        "balance": {
                          "value": 23.533,
                          "formattedWithUnit": "23.533 days",
                          "formattedWithUnitRoundedDown": "23.53 days",
                          "payable": true
                        },
                        "accrualSeparatedBalance": {
                          "value": 10,
                          "formattedWithUnit": "10 days",
                          "formattedWithUnitRoundedDown": "10 days",
                          "payable": false
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "403": {
            "$ref": "#/components/responses/403"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "sfOauth": {
        "type": "oauth2",
        "description": "Successfactors OAuth 2.0 flow. More information is available [here](https://help.sap.com/docs/SAP_SUCCESSFACTORS_PLATFORM/9f5f060351034d98990213d077dab38a/d9a9545305004187986c866de2b66987.html?locale=en-US)",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://{api-server}/oauth/token",
            "scopes": {}
          }
        }
      }
    },
    "schemas": {
      "TimeAccountBalanceResponse": {
        "type": "object",
        "properties": {
          "timeAccount": {
            "$ref": "#/components/schemas/TimeAccountResponse"
          },
          "balances": {
            "$ref": "#/components/schemas/DetailedBalanceResponse"
          }
        }
      },
      "TerminationTimeAccountBalanceResponse": {
        "type": "object",
        "description": "The response for the termination time account balance. The property accrualSeparatedBalance is only returned if the associated time account type has the entitlement method 'Entitled as Transferred' configured. The accrualSeparatedBalance is filled with the accrual balance that has not yet been transferred into an entitlement.",
        "properties": {
          "timeAccount": {
            "$ref": "#/components/schemas/TerminationTimeAccountResponse"
          },
          "balance": {
            "$ref": "#/components/schemas/AvailableBalanceResponse"
          },
          "accrualSeparatedBalance": {
            "$ref": "#/components/schemas/AvailableBalanceResponse"
          }
        }
      },
      "TimeAccountResponse": {
        "type": "object",
        "properties": {
          "timeAccountType": {
            "$ref": "#/components/schemas/TimeAccountTypeResponse"
          },
          "externalCode": {
            "type": "string",
            "example": "92f29d6bfafb40ac8cbca033744f50ad"
          },
          "bookableStartDate": {
            "type": "string",
            "example": "2023-01-01"
          },
          "bookableEndDate": {
            "type": "string",
            "example": "2024-06-30"
          },
          "nextTransferDate": {
            "type": "string",
            "example": "2023-02-01"
          }
        }
      },
      "TerminationTimeAccountResponse": {
        "type": "object",
        "properties": {
          "timeAccountType": {
            "$ref": "#/components/schemas/TimeAccountTypeResponse"
          },
          "externalCode": {
            "type": "string",
            "example": "92f29d6bfafb40ac8cbca033744f50ad"
          },
          "bookableStartDate": {
            "type": "string",
            "example": "2023-01-01"
          },
          "bookableEndDate": {
            "type": "string",
            "example": "2024-06-30"
          }
        }
      },
      "TimeAccountTypeResponse": {
        "type": "object",
        "properties": {
          "externalCode": {
            "type": "string",
            "example": "VAC-DAYS"
          },
          "externalName": {
            "type": "string",
            "example": "Vacation (Days)"
          },
          "unit": {
            "type": "string",
            "example": "DAYS"
          }
        }
      },
      "DetailedBalanceResponse": {
        "type": "object",
        "properties": {
          "available": {
            "$ref": "#/components/schemas/SimpleBalanceResponse"
          },
          "accrued": {
            "$ref": "#/components/schemas/SimpleBalanceResponse"
          },
          "earned": {
            "$ref": "#/components/schemas/SimpleBalanceResponse"
          },
          "paidOut": {
            "$ref": "#/components/schemas/SimpleBalanceResponse"
          },
          "planned": {
            "$ref": "#/components/schemas/SimpleBalanceResponse"
          },
          "taken": {
            "$ref": "#/components/schemas/SimpleBalanceResponse"
          }
        }
      },
      "SimpleBalanceResponse": {
        "type": "object",
        "properties": {
          "value": {
            "type": "number",
            "example": 23.533
          },
          "formattedWithUnit": {
            "type": "string",
            "example": "23.533 days",
            "description": "The balance with unit in requested users language format."
          },
          "formattedWithUnitRoundedDown": {
            "type": "string",
            "example": "23.53 days",
            "description": "The balance with unit rounded down to 2 decimal places in requested users language format."
          }
        }
      },
      "AvailableBalanceResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/SimpleBalanceResponse"
          },
          {
            "type": "object",
            "properties": {
              "payable": {
                "type": "boolean",
                "example": false,
                "description": "Indicator whether the balance can be paid out by the requested user or not."
              }
            }
          }
        ]
      },
      "TimeTypeBalanceResponse": {
        "type": "object",
        "properties": {
          "mainAbsenceTimeType": {
            "type": "boolean",
            "example": true
          },
          "timeType": {
            "$ref": "#/components/schemas/TimeTypeResponse"
          },
          "balance": {
            "$ref": "#/components/schemas/SimpleBalanceResponse"
          }
        }
      },
      "TimeTypeResponse": {
        "type": "object",
        "properties": {
          "externalCode": {
            "type": "string",
            "example": "VAC"
          },
          "externalName": {
            "type": "string",
            "example": "Vacation (Days)"
          },
          "unit": {
            "type": "string",
            "example": "DAYS"
          },
          "leaveOfAbsence": {
            "type": "boolean",
            "example": false
          },
          "undeterminedEndDateAllowed": {
            "type": "boolean",
            "example": false
          }
        }
      },
      "BadRequest": {
        "title": "Bad Request",
        "description": "Response body",
        "type": "object",
        "properties": {
          "error": {
            "title": "Error",
            "type": "object",
            "properties": {
              "code": {
                "title": "Code",
                "type": "string",
                "example": "BadRequest"
              },
              "message": {
                "title": "Message",
                "type": "string",
                "example": "Please enter a valid date."
              }
            }
          }
        }
      },
      "Forbidden": {
        "title": "Forbidden",
        "description": "Response body",
        "type": "object",
        "properties": {
          "error": {
            "title": "Error",
            "type": "object",
            "properties": {
              "code": {
                "title": "Code",
                "type": "string",
                "example": "Forbidden"
              },
              "message": {
                "title": "Message",
                "type": "string",
                "example": "You can't access the requested resource."
              }
            }
          }
        }
      },
      "NotFound": {
        "title": "Not Found",
        "description": "Response body",
        "type": "object",
        "properties": {
          "error": {
            "title": "Error",
            "type": "object",
            "properties": {
              "code": {
                "title": "Code",
                "type": "string",
                "example": "NotFound"
              },
              "message": {
                "title": "Message",
                "type": "string",
                "example": "The requested resource could not be found."
              }
            }
          }
        }
      },
      "InternalServerError": {
        "title": "InternalServerError",
        "description": "Response body",
        "type": "object",
        "properties": {
          "error": {
            "title": "Error",
            "type": "object",
            "properties": {
              "code": {
                "title": "Code",
                "type": "string",
                "example": "InternalError"
              },
              "message": {
                "title": "Message",
                "type": "string",
                "example": "An unexpected error has occurred. Please contact the system administrator."
              }
            }
          }
        }
      }
    },
    "responses": {
      "400": {
        "description": "It indicates that the server cannot process the request due to something that is perceived to be a client error. For example, any validation error in the request.",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/BadRequest"
            }
          }
        }
      },
      "403": {
        "description": "It indicates that the server understood the request, but refuses to authorize it.",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Forbidden"
            }
          }
        }
      },
      "404": {
        "description": "It indicates that the server could not find the requested resource and could not fulfill the request.",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/NotFound"
            }
          }
        }
      },
      "500": {
        "description": "It indicates that the server encountered an unexpected condition that prevented it from fulfilling the request.",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/InternalServerError"
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "sfOauth": []
    }
  ],
  "externalDocs": {
    "description": "More information about this API is available in help.sap.com",
    "url": "https://help.sap.com/docs/SAP_SUCCESSFACTORS_EMPLOYEE_CENTRAL/68de09dff990417b9f0acf6ccc13a14d/9872a67cc9be4066a9cc2731f9c542a8.html?state=LATEST"
  },
  "x-sap-api-type": "REST",
  "x-sap-shortText": "APIs for SAP SuccessFactors Time Management."
}