{
  "openapi": "3.0.1",
  "info": {
    "title": "Position Budgeting Control for Cloud",
    "description": "You can use this API to perform Position Budgeting Control tasks such as reading the employee financing data for active and previous financing periods, reading and updating the list of symbolic accounts, and reading and updating the list of employee groupings. This API is implemented based on the REST specification. You can find your company's API server in [List of API Servers in SAP SuccessFactors.](https://help.sap.com/viewer/d599f15995d348a1b45ba5603e2aba9b/LATEST/en-US/af2b8d5437494b12be88fe374eba75b6.html)",
    "version": "1.0"
  },
  "x-sap-shortText": "Manage Position Budgeting Control aspects such as employee financing, symbolic accounts, and employee groupings.",
  "externalDocs": {
    "description": "More information available in help.sap.com",
    "url": "https://help.sap.com/docs/successfactors-employee-central/implementing-position-budgeting-control-for-cloud/public-apis-for-position-budgeting-control-for-cloud"
  },
  "servers": [
    {
      "url": "https://sandbox.api.sap.com/SFPublicSectorManagement",
      "description": "Sandbox server"
    },
    {
      "url": "https://{api-server}/rest/workforce/positionbudgetcontrol/v1",
      "description": "REST APIs for the SuccessFactors Data Centers",
      "variables": {
        "api-server": {
          "description": "SuccessFactors Data Center host",
          "default": "apisalesdemo8.successfactors.com"
        }
      }
    }
  ],
  "paths": {
    "/employeeFinancingData": {
      "get": {
        "summary": "Get employee financing data",
        "description": "You can use this API to read the employee financing data for active and previous financing periods. This API allows the payroll systems to replicate the employee financing information (HR Reference document number, Reference Earmarked document number, corresponding budget address and amount, and document status) from Position Budgeting Control to your payroll system. This API is implemented based on REST specification.",
        "tags": ["Employee Financing"],
        "operationId": "getEmployeeFinancing",
        "parameters": [
          {
            "name": "lastKnownReplicationTimeStamp",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "format": "date-time"
            }
          },
          {
            "name": "objectIds",
            "in": "query",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          {
            "name": "financingPeriod",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "$top",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 100
            }
          },
          {
            "name": "$skip",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int64",
              "default": 0
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Correlation-ID": {
                "$ref": "#/components/headers/X-Correlation-ID"
              }
            },
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/PBCReplicationStatusHeader"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "403": {
            "$ref": "#/components/responses/403"
          }
        }
      }
    },
    "/symbolicAccounts": {
      "get": {
        "summary": "Get list of symbolic accounts",
        "description": "You can use this API to read the list of symbolic accounts. To manage Earmarked Fund Documents from Position Budgeting Control, you must provide information about Symbolic Account. Therefore, during the Position Budgeting Control configuration, you must provide the mapping between the Position Budgeting Control applicable Pay Component to Symbolic Account in Position Budgeting Control. This API is implemented based on REST specification.",
        "tags": ["Symbolic Accounts"],
        "operationId": "getSymbolicAccounts",
        "parameters": [
          {
            "name": "countryCode",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "payComponentId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          {
            "name": "accountAssignmentType",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "validFrom",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "format": "date"
            }
          },
          {
            "name": "validTo",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "format": "date"
            }
          },
          {
            "name": "symbolicAccount",
            "in": "query",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Correlation-ID": {
                "$ref": "#/components/headers/X-Correlation-ID"
              }
            },
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SymbolicAccountData"
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "403": {
            "$ref": "#/components/responses/403"
          }
        }
      },
      "patch": {
        "summary": "Save list of symbolic accounts",
        "description": "You can use this API to update the list of symbolic accounts. To manage Earmarked Fund Documents from Position Budgeting Control, you must provide information about Symbolic Account. Therefore, during the Position Budgeting Control configuration, you must provide the mapping between the Position Budgeting Control applicable Pay Component to Symbolic Account in Position Budgeting Control. This API is implemented based on REST specification.",
        "tags": ["Symbolic Accounts"],
        "operationId": "saveSymbolicAccounts",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SymbolicAccountRequestStructure"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Correlation-ID": {
                "$ref": "#/components/headers/X-Correlation-ID"
              }
            },
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "204": {
            "description": "The resource was edited successfully."
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "403": {
            "$ref": "#/components/responses/403"
          }
        }
      }
    },
    "/employeeGroupings": {
      "get": {
        "summary": "Get list of employee groupings",
        "description": "You can use this API to read the list of employee groupings. To manage Earmarked Fund Documents from Position Budgeting Control, you must provide information about Employee Grouping. Therefore, during the Position Budgeting Control configuration, you must provide the mapping between the Position Budgeting Control applicable Employee Class and Employment Type to Employee Grouping in Position Budgeting Control. This API is implemented based on REST specification.",
        "tags": ["Employee Groupings"],
        "operationId": "getEmployeeGrouping",
        "parameters": [
          {
            "name": "countryCode",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "employeeClass",
            "in": "query",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          {
            "name": "employmentType",
            "in": "query",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          {
            "name": "validFrom",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "format": "date"
            }
          },
          {
            "name": "validTo",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "format": "date"
            }
          },
          {
            "name": "employeeGroup",
            "in": "query",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Correlation-ID": {
                "$ref": "#/components/headers/X-Correlation-ID"
              }
            },
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/EmployeeGroupingData"
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "403": {
            "$ref": "#/components/responses/403"
          }
        }
      },
      "patch": {
        "summary": "Save list of employee groupings",
        "description": "You can use this API to update the list of employee groupings. To manage Earmarked Fund Documents from Position Budgeting Control, you must provide information about Employee Grouping. Therefore, during the Position Budgeting Control configuration, you must provide the mapping between the Position Budgeting Control applicable Employee Class and Employment Type to Employee Grouping in Position Budgeting Control. This API is implemented based on REST specification.",
        "tags": ["Employee Groupings"],
        "operationId": "saveEmployeeGrouping",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/EmployeeGroupingRequestStructure"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Correlation-ID": {
                "$ref": "#/components/headers/X-Correlation-ID"
              }
            },
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "204": {
            "description": "The resource was edited successfully."
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "403": {
            "$ref": "#/components/responses/403"
          }
        }
      }
    },
    "/replicationStatuses": {
      "patch": {
        "summary": "Save list of Replication Statuses",
        "description": "You can use this API to update the list of Replication Statuses.",
        "tags": ["Replication Statuses"],
        "operationId": "saveReplicationStatuses",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ReplicationStatusesRequestStructure"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Correlation-ID": {
                "$ref": "#/components/headers/X-Correlation-ID"
              }
            },
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "204": {
            "description": "The resource was edited successfully."
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "403": {
            "$ref": "#/components/responses/403"
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Employee Financing",
      "description": "Operations related to Employee Financing"
    },
    {
      "name": "Symbolic Accounts",
      "description": "Operations related to symbolic account mappings"
    },
    {
      "name": "Employee Groupings",
      "description": "Operations related to employee grouping rules"
    },
    {
      "name": "Replication Statuses",
      "description": "Operations related to replication statuses rules"
    }
  ],
  "components": {
    "schemas": {
      "Error": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "example": "NotFound"
          },
          "message": {
            "type": "string",
            "example": "Could not retrieve symbolic account data."
          },
          "details": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "code",
                "message"
              ],
              "properties": {
                "code": {
                  "type": "string",
                  "example": "COE0018"
                },
                "message": {
                  "type": "string",
                  "example": "Could not retrieve employee grouping data."
                }
              }
            }
          }
        }
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "error": {
            "$ref": "#/components/schemas/Error"
          }
        },
        "description": "ErrorResponse",
        "example": {
          "error": {
            "code": "400",
            "message": "BadRequest",
            "details": [
              {
                "code": "400",
                "message": "BadRequest"
              }
            ]
          }
        }
      },
      "PBCMessage": {
        "type": "object",
        "properties": {
          "messageKey": {
            "example": "POSITION_BUDGET_CONTROL_REPLICATION_RECORDS_FOUND",
            "title": "Message key",
            "type": "string"
          },
          "messageString": {
            "example": "The requested employee records were found.",
            "title": "Message string",
            "type": "string"
          }
        }
      },
      "PBCReplicationData": {
        "properties": {
          "id": {
            "example": "Carla Grant",
            "title": "User ID",
            "maxLength": 100,
            "type": "string"
          },
          "objectType": {
            "example": "EMP",
            "title": "Object type",
            "maxLength": 3,
            "type": "string"
          },
          "startDate": {
            "example": "2024-04-01",
            "title": "Financing period start date",
            "type": "string",
            "format": "date"
          },
          "endDate": {
            "example": "2025-03-31",
            "title": "Financing period end date",
            "type": "string",
            "format": "date"
          },
          "companyCode": {
            "example": "1710",
            "title": "Company code",
            "type": "string",
            "format": "string"
          },
          "creationDate": {
            "example": "2024-04-23",
            "title": "Run creation date",
            "type": "string",
            "format": "date"
          },
          "status": {
            "example": "ERR",
            "title": "Financing status",
            "maxLength": 3,
            "type": "string"
          },
          "payLocked": {
            "example": "F",
            "title": "Payroll lock",
            "maxLength": 1,
            "type": "string"
          },
          "recalActive": {
            "example": "F",
            "title": "Recalculation active",
            "maxLength": 1,
            "type": "string"
          },
          "financingStatusEffectiveDate": {
            "example": "2024-04-23",
            "title": "Financing status effective date",
            "type": "string",
            "format": "date"
          },
          "allDocsReleased": {
            "example": true,
            "title": "Overall commitment document completion indicator",
            "type": "boolean"
          },
          "replicationFinancingHeaders": {
            "items": {
              "$ref": "#/components/schemas/PBCReplicationFinancingHeader"
            },
            "type": "array"
          }
        },
        "type": "object"
      },
      "PBCReplicationFinancingHeader": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "objectType": {
            "type": "string"
          },
          "startDate": {
            "type": "string",
            "format": "date"
          },
          "endDate": {
            "type": "string",
            "format": "date"
          },
          "hrDocRefNumber": {
            "type": "string"
          },
          "earmarkedFundDocumentId": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "logicalSystemOfSourceDoc": {
            "type": "string"
          },
          "documentType": {
            "type": "string"
          },
          "replicationFinancingItems": {
            "items": {
              "$ref": "#/components/schemas/PBCReplicationFinancingItem"
            },
            "type": "array"
          }
        }
      },
      "PBCReplicationFinancingItem": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "objectType": {
            "type": "string"
          },
          "startDate": {
            "type": "string",
            "format": "date"
          },
          "endDate": {
            "type": "string",
            "format": "date"
          },
          "glAccount": {
            "type": "string"
          },
          "earmarkedFundsAmount": {
            "type": "number"
          },
          "currency": {
            "type": "string"
          },
          "completionIndicator": {
            "type": "string"
          },
          "companyCode": {
            "type": "string"
          },
          "costCenter": {
            "type": "string"
          },
          "wbsElement": {
            "type": "string"
          },
          "grant": {
            "type": "string"
          },
          "fund": {
            "type": "string"
          },
          "budgetPeriod": {
            "type": "string"
          },
          "functionalArea": {
            "type": "string"
          },
          "fundsCenter": {
            "type": "string"
          },
          "hrDocRefItemId": {
            "type": "string"
          },
          "earmarkedFundDocumentItemId": {
            "type": "string"
          },
          "hrDocReferenceId": {
            "type": "string"
          }
        }
      },
      "PBCReplicationStatusHeader": {
        "type": "object",
        "properties": {
          "message": {
            "$ref": "#/components/schemas/PBCMessage"
          },
          "employeeFinancingList": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PBCReplicationData"
            },
            "example": [
              {
                "id": "Carla Grant",
                "objectType": "EMP",
                "startDate": "2024-04-01",
                "endDate": "2025-03-31",
                "companyCode": "1710",
                "creationDate": "2024-04-23",
                "status": "ERR",
                "payLocked": "F",
                "recalActive": "F",
                "financingStatusEffectiveDate": "2024-04-23",
                "allDocsReleased": true,
                "replicationFinancingHeaders": [
                  {
                    "id": "Carla Grant",
                    "objectType": "EMP",
                    "startDate": "2024-04-01",
                    "endDate": "2024-06-30",
                    "hrDocRefNumber": "100011",
                    "earmarkedFundDocumentId": "299191",
                    "logicalSystemOfSourceDoc": "C10CLNT117",
                    "documentType": "COM",
                    "replicationFinancingItems": [
                      {
                        "id": "Carla Grant",
                        "objectType": "EMP",
                        "startDate": "2024-04-01",
                        "endDate": "2024-04-30",
                        "glAccount": "62229889",
                        "earmarkedFundsAmount": 200,
                        "currency": "USD",
                        "completionIndicator": "F",
                        "companyCode": "1710",
                        "costCenter": "17101101",
                        "wbsElement": "WBS1001",
                        "grant": "NRG",
                        "fund": "G1100",
                        "budgetPeriod": "2024",
                        "functionalArea": "1000",
                        "fundsCenter": "1710100",
                        "earmarkedFundDocumentItemId": "1",
                        "hrDocRefItemId": "1"
                      }
                    ]
                  }
                ]
              }
            ]
          }
        }
      },
      "ReplicationStatusesRequestStructure": {
        "type": "object",
        "properties": {
          "value": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ReplicationStatusesData"
            },
            "example": [
              {
                "objectId": "natsu",
                "objectType": "EMP",
                "startDate": "2025-01-01",
                "endDate": "2025-12-31",
                "status": "SUC",
                "timestamp": "2025-03-19T10:17:23Z",
                "allDocsReleased": false
              }
            ]
          }
        }
      },
      "ReplicationStatusesData": {
        "type": "object",
        "properties": {
          "objectId": {
            "type": "string",
            "example": "string"
          },
          "objectType": {
            "type": "string",
            "example": "string"
          },
          "startDate": {
            "type": "string",
            "format": "date",
            "example": "yyyy-mm-dd"
          },
          "endDate": {
            "type": "string",
            "format": "date",
            "example": "yyyy-mm-dd"
          },
          "status": {
            "type": "string",
            "example": "string"
          },
          "timestamp": {
            "type": "string",
            "format": "date-time",
            "example": "/Date(1492098664000)/"
          },
          "allDocsReleased": {
            "type": "boolean",
            "example": true
          }
        }
      },
      "SymbolicAccountRequestStructure": {
        "type": "object",
        "properties": {
          "value": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/SymbolicAccountData"
            },
            "example": [
              {
                "id": "d0fac571-4e4c-45f8-acda-35d0ec1ba834",
                "countryCode": "US",
                "payComponentId": "US_M001",
                "accountAssignmentType": "C",
                "validFrom": "2025-01-01",
                "validTo": "2025-12-31",
                "symbolicAccount": "1100",
                "lastModifiedTimestamp": "2025-06-06T10:56:43.651064100Z"
              }
            ]
          }
        }
      },
      "SymbolicAccountData": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": "string"
          },
          "countryCode": {
            "type": "string",
            "example": "string"
          },
          "payComponentId": {
            "type": "string",
            "example": "string"
          },
          "accountAssignmentType": {
            "type": "string",
            "example": "string"
          },
          "validFrom": {
            "type": "string",
            "format": "date",
            "example": "/Date(1492098664000)/"
          },
          "validTo": {
            "type": "string",
            "format": "date",
            "example": "/Date(1492098664000)/"
          },
          "symbolicAccount": {
            "type": "string",
            "example": "string"
          },
          "lastModifiedTimestamp": {
            "type": "string",
            "format": "date-time",
            "example": "/Date(1492098664000)/"
          }
        }
      },
      "EmployeeGroupingData": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": "string"
          },
          "countryCode": {
            "type": "string",
            "example": "string"
          },
          "employeeClass": {
            "type": "string",
            "example": "string"
          },
          "employmentType": {
            "type": "string",
            "example": "string"
          },
          "validFrom": {
            "type": "string",
            "format": "date",
            "example": "/Date(1492098664000)/"
          },
          "validTo": {
            "type": "string",
            "format": "date",
            "example": "/Date(1492098664000)/"
          },
          "employeeGroup": {
            "type": "string",
            "example": "string"
          },
          "lastModifiedTimestamp": {
            "type": "string",
            "format": "date-time",
            "example": "/Date(1492098664000)/"
          }
        }
      },
      "EmployeeGroupingRequestStructure": {
        "type": "object",
        "properties": {
          "value": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/EmployeeGroupingData"
            },
            "example": [
              {
                "id": "2ff4aff4-3643-459e-8c36-9d19eb030d95",
                "countryCode": "US",
                "employeeClass": "EMPLOYEE",
                "employmentType": "SALARIED EXEMPT",
                "validFrom": "2025-01-01",
                "validTo": "2025-12-31",
                "employeeGroup": "1",
                "lastModifiedTimestamp": "2025-06-06T10:58:21.030232900Z"
              }
            ]
          }
        }
      }
    },
    "responses": {
      "400": {
        "description": "Bad Request",
        "headers": {
          "X-Correlation-ID": {
            "$ref": "#/components/headers/X-Correlation-ID"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      },
      "401": {
        "description": "Unauthorized",
        "headers": {
          "X-Correlation-ID": {
            "$ref": "#/components/headers/X-Correlation-ID"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      },
      "403": {
        "description": "Forbidden",
        "headers": {
          "X-Correlation-ID": {
            "$ref": "#/components/headers/X-Correlation-ID"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      },
      "404": {
        "description": "Not Found",
        "headers": {
          "X-Correlation-ID": {
            "$ref": "#/components/headers/X-Correlation-ID"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      },
      "409": {
        "description": "Conflict",
        "headers": {
          "X-Correlation-ID": {
            "$ref": "#/components/headers/X-Correlation-ID"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      },
      "412": {
        "description": "Precondition Failed",
        "headers": {
          "X-Correlation-ID": {
            "$ref": "#/components/headers/X-Correlation-ID"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      },
      "413": {
        "description": "Payload Too Large",
        "headers": {
          "X-Correlation-ID": {
            "$ref": "#/components/headers/X-Correlation-ID"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      },
      "429": {
        "description": "Too Many Requests",
        "headers": {
          "Retry-After": {
            "$ref": "#/components/headers/Retry-After"
          },
          "X-Correlation-ID": {
            "$ref": "#/components/headers/X-Correlation-ID"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      },
      "500": {
        "description": "Internal Server Error",
        "headers": {
          "X-Correlation-ID": {
            "$ref": "#/components/headers/X-Correlation-ID"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      },
      "503": {
        "description": "Service Unavailable",
        "headers": {
          "Retry-After": {
            "$ref": "#/components/headers/Retry-After"
          },
          "X-Correlation-ID": {
            "$ref": "#/components/headers/X-Correlation-ID"
          }
        },
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      }
    },
    "headers": {
      "Retry-After": {
        "description": "It indicates how long the client should wait before making a follow-up request.",
        "schema": {
          "type": "integer"
        }
      },
      "X-Correlation-ID": {
        "description": "One unique id which is able to identify the whole request.",
        "schema": {
          "type": "string",
          "format": "uuid"
        }
      }
    },
    "securitySchemes": {
      "jwt": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
